Squashed commit of the following:
commit f096dfe411b75bcae7325ea1c6f265d5091ede89
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Wed Feb 5 18:50:52 2025 -0600

    minor fixes

commit a91ea173620123b0fc8d9ca1a971de153756ac09
Author: Eduardo <eduarbo@liz-macbook-air.local>
Date:   Wed Nov 20 18:31:12 2024 -0800

    emacs: fix issue when uniquifying buffer name

commit 5e5c200c80ca996a1fa69051e921d28d30d8dcfd
Author: Eduardo <eduarbo@liz-macbook-air.local>
Date:   Wed Nov 20 17:31:58 2024 -0800

    fix init script for karabiner

commit 6e119848b78b126744ff4e818fc92a74ac398bd9
Author: Eduardo <eduarbo@liz-macbook-air.local>
Date:   Mon Nov 18 22:38:13 2024 -0600

    fixes

commit d419bf4c0af37732faca4fb8f99104c061c614a5
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Mon Nov 18 22:20:46 2024 -0600

    fix slash

commit 14f72910113fde79bfce33ae40bd5f1e9a1e1698
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Mon Nov 18 22:19:13 2024 -0600

    comments

commit 5aba80c4ee367027920f915a1c5e5e5e532750b4
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Sun Nov 17 12:35:09 2024 -0600

    fix CAPSLOCK bindings

commit 3f4c171ee25600b60785b66059bce76be5bfe098
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Sun Nov 17 12:32:51 2024 -0600

    swap keys

commit e234fc2f2e866f746a21235cd1dd3fd631339718
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Sun Nov 17 12:17:49 2024 -0600

    revert changes on modifiers and remap accents

commit 6533b7e59373b19ea13f5151d0307800cbec9ccc
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Sun Nov 17 11:42:57 2024 -0600

    swap space bar and left command

commit 28ed6e86033f962790519dbead4831369cd1293b
Author: Eduardo Ruiz Macias <eduarbo@gmail.com>
Date:   Sun Nov 17 11:18:52 2024 -0600

    remap comma and period for shifted symbols layer

diff --git a/macos/karabiner/_init b/macos/karabiner/_init
--- a/macos/karabiner/_init
+++ b/macos/karabiner/_init
@@ -11,7 +11,7 @@ brew_deps=(
 )
 
 link() {
-  mklink json/* $KARABINER_CONFIG_DIR
+  mklink json $KARABINER_CONFIG_DIR
   echo-info "Profile names"
   karabiner --list-profile-names
 }
@@ -20,42 +20,37 @@ install() {
   brew install ${brew_deps[@]}
 
   # TODO Extract karabiner.json generator to its own repo
-  # if _is_callable nodenv; then
-  #   echo "Installing required node version"
-  #   nodenv install < .node-version
-  # else
-  #   echo "Make sure to install the required node version"
-  # fi
-
-  # npm install
-
-  # build
+  if _is_callable nodenv; then
+    echo-info "Installing required node version"
+    nodenv install < .node-version
+    npm install
+    build
+  else
+    echo-alert "Make sure to install the required node version to regenerate config from source files"
+  fi
 }
 
 update() {
-  build
-  # Re-link files to ensure Karabiner detects the updates and reloads the configuration
-  link
+  if _is_callable node; then
+    build
+  else
+    link
+  fi
 }
 
 clean() {
-  rm -rfv "$KARABINER_CONFIG_DIR"/{karabiner.json,assets}
+  rm -rfv "$KARABINER_CONFIG_DIR"
 }
 
 build() {
   npm run build
 
+  # validate complex modifications
   echo-info "Check Complex Modifications"
-  karabiner --lint-complex-modifications "$KARABINER_CONFIG_DIR"/assets/complex_modifications/* || {
+  karabiner --lint-complex-modifications json/assets/complex_modifications/* || {
     echo-fail "Invalid Complex Modifications"
     exit 1
   }
-
-  # copy json files instead of linking them to force karabiner to reload the conf
-  echo-info "copy json files and reload the conf"
-
-  echo-info "Profile names"
-  karabiner --list-profile-names
 }
 
 init "$@"
